"""Add full_name and status columns to User table

Revision ID: add_user_full_name_status
Revises: 272698cc9673
Create Date: 2025-01-04 22:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_full_name_status'
down_revision = 'route_assignment_update'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE user SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE user SET full_name = username WHERE full_name IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('full_name')
    # ### end Alembic commands ###